spring.application.name=scaa
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath*:/create.sql
spring.sql.init.data-locations=classpath*:/insert.sql
spring.sql.init.encoding=UTF-8

eureka.client.serviceUrl.defaultZone=http://nameserver:8761/eureka